# Generated by Django 4.1.1 on 2023-01-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0002_alter_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userproduct',
            name='is_notified',
        ),
        migrations.AddField(
            model_name='userproduct',
            name='price_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
