# Generated by Django 4.1.1 on 2023-02-01 14:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('box', '0003_remove_userproduct_is_notified_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userproduct',
            unique_together={('user', 'product')},
        ),
    ]
