# Generated by Django 4.1.1 on 2023-02-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0004_alter_userproduct_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userproduct',
            name='wanted_price',
            field=models.FloatField(default=0),
        ),
    ]
