# Generated by Django 4.1.1 on 2023-02-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0006_draftcollection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraftCollection',
        ),
    ]
