# Generated by Django 4.1.1 on 2023-02-14 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DraftCollection',
        ),
    ]
